
SbOLED.init()
SbOLED.writeStringNewLine("the quick brown fox jumped over the lazy dog?")
SbOLED.writeStringNewLine("THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG!")
basic.pause(1000)
SbOLED.clear()
SbOLED.writeString("Your magic number is ")
SbOLED.writeNum(23 * 3)
SbOLED.writeStringNewLine("!")
SbOLED.writeNumNewLine(1)
basic.pause(100)
SbOLED.writeNumNewLine(2)
basic.pause(100)
SbOLED.writeNumNewLine(3)
basic.pause(1000)
for (let i = 0; i < 100; i++) {
    SbOLED.drawLoading(i)
}
basic.pause(1000)
SbOLED.clear()
SbOLED.drawRectangle(10, 10, 60, 60)
SbOLED.drawLine(0, 0, 128, 64)
SbOLED.drawLine(0, 64, 128, 0)
